'use strict';

// Codex delivery of the nubosloop roles as spawnable subagents.
//
// Codex scans `.codex/agents/*.toml` (project) and `~/.codex/agents/*.toml`
// (personal); one file defines one agent. Required fields are `name`,
// `description` and `developer_instructions`; `model`, `model_reasoning_effort`,
// `sandbox_mode`, `nickname_candidates` and `mcp_servers` are optional and
// inherit from the parent session when omitted.
// https://developers.openai.com/codex/subagents
//
// This is the surface that gives Codex the *isolation* the loop assumes: a
// spawned subagent runs in its own thread, so a critic no longer shares context
// with the executor it reviews. Delegation is requested in the prompt; the
// parent caps concurrency via `agents.max_threads` (default 6) and nesting via
// `agents.max_depth` (default 1).
//
// Model and sandbox are deliberately not emitted. nubos-pilot addresses models
// by tier (`sonnet`/`opus`) and Codex resolves them by profile, so a mapping
// would be a guess that silently pins the wrong model; inheriting the parent is
// both correct and what the tier already meant. The tier is preserved as
// reference text inside the instructions.

const path = require('node:path');
const { extractFrontmatter } = require('../frontmatter.cjs');
const { NubosPilotError } = require('../core.cjs');

// TOML basic strings process escapes, and agent prose contains regexes like
// `\d` — an invalid escape there is a parse error, not a cosmetic issue. So
// scalars are escaped explicitly and the body uses a multi-line *literal*
// string, which processes nothing at all.
function _basicString(value) {
  const escaped = String(value)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n')
    .replace(/\t/g, '\\t');
  return '"' + escaped + '"';
}

// The one thing a literal string cannot carry is its own delimiter.
function _literalBlock(body, sourceFile) {
  if (body.includes("'''")) {
    throw new NubosPilotError(
      'codex-agent-undelimitable-body',
      "Agent body contains ''' and cannot be emitted as a TOML literal string",
      { sourceFile },
    );
  }
  return "'''\n" + body.replace(/\s*$/, '') + "\n'''";
}

function agentNameFor(sourceFile) {
  const base = path.basename(String(sourceFile)).replace(/\.md$/i, '');
  if (!base) {
    throw new NubosPilotError(
      'codex-agent-invalid-source',
      'Cannot derive an agent name from an empty basename',
      { sourceFile },
    );
  }
  return base;
}

function renderAgentToml({ sourceFile, content }) {
  let parsed;
  try {
    parsed = extractFrontmatter(content) || {};
  } catch (err) {
    throw new NubosPilotError(
      'codex-agent-unparsable-source',
      'Could not parse frontmatter of ' + sourceFile,
      { sourceFile, cause: err && err.code ? err.code : String(err) },
    );
  }
  const fm = parsed.frontmatter || {};
  const body = parsed.body || '';

  const name = typeof fm.name === 'string' && fm.name.trim()
    ? fm.name.trim()
    : agentNameFor(sourceFile);
  const description = typeof fm.description === 'string' ? fm.description.replace(/\s+/g, ' ').trim() : '';
  if (!description) {
    // Codex matches on `description` when deciding which agent to spawn, so an
    // empty one makes the role unreachable by delegation.
    throw new NubosPilotError(
      'codex-agent-missing-description',
      'Codex agents require a description; ' + sourceFile + ' has none',
      { sourceFile },
    );
  }

  const tier = typeof fm.tier === 'string' ? fm.tier.trim() : '';
  const tools = typeof fm.tools === 'string' ? fm.tools.trim() : '';
  const preamble = [
    '<!-- Generated by nubos-pilot from agents/' + path.basename(sourceFile)
      + '. Do not edit here; edit the agent. -->',
    '',
    tier ? 'Reference tier: `' + tier + '` (Codex resolves the model by profile; this'
      + ' subagent inherits the parent session\'s model).' : null,
    tools ? 'Reference tools: `' + tools + '`.' : null,
    tier || tools ? '' : null,
  ].filter((l) => l !== null).join('\n');

  const toml = [
    'name = ' + _basicString(name),
    'description = ' + _basicString(description),
    'developer_instructions = ' + _literalBlock(preamble + '\n' + body.replace(/^\s+/, ''), sourceFile),
    '',
  ].join('\n');

  return { name, content: toml };
}

module.exports = { agentNameFor, renderAgentToml };
