'use strict';

// Codex delivery of workflows and agent roles.
//
// Codex has no project-scoped command directory: custom prompts load only from
// $CODEX_HOME/prompts (openai/codex#9848, #4734 are the open requests for
// `.codex/prompts`), they are user-global, and OpenAI marks them deprecated in
// favour of skills. Skills are the one surface that is project-scoped
// (`.codex/skills/`), repo-shareable and discoverable, so the `/np:*` workflows
// ship as skills. The loop *roles* take the other Codex surface — spawnable
// subagents in `.codex/agents/*.toml`, see codex-agents.cjs.
//
// Codex is still not Claude in one respect the rendered header states outright:
// a skill is invoked with `$name`, not `/name` (openai/codex#11817 — `/<skill>`
// is unrecognised).

const path = require('node:path');
const { extractFrontmatter } = require('../frontmatter.cjs');
const { NubosPilotError } = require('../core.cjs');

function skillNameFor(prefix, sourceFile) {
  const base = path.basename(String(sourceFile)).replace(/\.md$/i, '');
  if (!base) {
    throw new NubosPilotError(
      'codex-skill-invalid-source',
      'Cannot derive a skill name from an empty basename',
      { sourceFile },
    );
  }
  return base.startsWith(prefix) ? base : prefix + base;
}

// Codex parses this with a real YAML parser, so the frontmatter is produced by
// one rather than hand-escaped. Descriptions are collapsed to a single line
// first: `description` is what Codex shows in `/skills` and matches against for
// implicit invocation, and a folded block there buys nothing.
function _yamlFrontmatter(fields) {
  const YAML = require('yaml');
  const collapsed = { ...fields, description: String(fields.description).replace(/\s+/g, ' ').trim() };
  return '---\n' + YAML.stringify(collapsed, { lineWidth: 0 }) + '---\n';
}

function _parseSource(content, sourceFile) {
  try {
    const parsed = extractFrontmatter(content) || {};
    return { fm: parsed.frontmatter || {}, body: parsed.body || '' };
  } catch (err) {
    throw new NubosPilotError(
      'codex-skill-unparsable-source',
      'Could not parse frontmatter of ' + sourceFile,
      { sourceFile, cause: err && err.code ? err.code : String(err) },
    );
  }
}

function _requireDescription(fm, sourceFile) {
  const desc = fm && typeof fm.description === 'string' ? fm.description.trim() : '';
  if (!desc) {
    throw new NubosPilotError(
      'codex-skill-missing-description',
      'Codex skills require a description; ' + sourceFile + ' has none',
      { sourceFile },
    );
  }
  return desc;
}

function _render({ name, description, userInvocable, header, body }) {
  const fm = _yamlFrontmatter({ name, description, 'user-invocable': userInvocable });
  const trimmedBody = String(body).replace(/^\s+/, '');
  return fm + header + '\n\n' + trimmedBody.replace(/\s*$/, '') + '\n';
}

// A workflow. The command name (`np:plan-phase`) is what every doc, workflow
// cross-reference and error hint says, so it stays in the header — the header
// is where the reader learns it maps to `$np-plan-phase` here.
function renderWorkflowSkill({ sourceFile, content, prefix }) {
  const { fm, body } = _parseSource(content, sourceFile);
  const name = skillNameFor(prefix, sourceFile);
  const description = _requireDescription(fm, sourceFile);
  const command = typeof fm.command === 'string' && fm.command
    ? fm.command
    : 'np:' + name.replace(new RegExp('^' + prefix), '');
  const argHint = typeof fm['argument-hint'] === 'string' ? fm['argument-hint'].trim() : '';

  const invocation = '`$' + name + (argHint ? ' ' + argHint : '') + '`';
  const header = [
    '<!-- Generated by nubos-pilot from workflows/' + path.basename(sourceFile)
      + '. Do not edit here; edit the workflow. -->',
    '',
    '> **Codex invocation:** ' + invocation + '. In Claude Code the same workflow is `/'
      + command + '`; Codex skills are invoked with `$`, not `/` — `/skills` lists them.',
  ].join('\n');

  return { name, content: _render({ name, description, userInvocable: true, header, body }) };
}

module.exports = { skillNameFor, renderWorkflowSkill };
