'use strict';

const { NubosPilotError } = require('../../core.cjs');

const CI_WORD_RE = /^[A-Za-z0-9_]+$/;

function ci(word) {
  if (typeof word !== 'string' || !CI_WORD_RE.test(word)) {
    throw new NubosPilotError(
      'secrets-keyword-unsafe',
      'a case-insensitive keyword must match [A-Za-z0-9_]+',
      { word: String(word) },
    );
  }
  let out = '';
  for (const ch of word) {
    const lower = ch.toLowerCase();
    const upper = ch.toUpperCase();
    out += lower === upper ? ch : '[' + lower + upper + ']';
  }
  return out;
}

const GAP = '[_.\\-]?';
const SEP = '["\']?\\s*(?:[:=]|=>)\\s*["\']?';

function keyword(parts) {
  return parts.join(GAP);
}

function optional(source) {
  return '(?:' + source + GAP + ')?';
}

function anyOf(sources) {
  return '(?:' + sources.join('|') + ')';
}

function assigned(keySource, valueSource) {
  return keySource + SEP + valueSource;
}

const FIXTURE_EXCLUDE_PATHS = Object.freeze([
  '**/*.example',
  '**/*.sample',
  '**/*.template',
  '**/*.dist',
  '**/fixtures/**',
  '**/__fixtures__/**',
  '**/testdata/**',
]);

const GENERIC_EXCLUDE_PATHS = Object.freeze([
  ...FIXTURE_EXCLUDE_PATHS,
  '**/*.test.*',
  '**/*.spec.*',
  '**/*.md',
]);

const HARDCODED = 'CWE-798';
const UNPROTECTED = 'CWE-522';

const RULES = [
  {
    id: 'NPS-0100',
    rule_name: 'aws_secret_access_key',
    category: 'cloud-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: assigned(
      keyword([ci('aws'), ci('secret'), ci('access'), ci('key')]),
      '[A-Za-z0-9/+=]{40}(?![A-Za-z0-9/+=])',
    ),
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'AWS secret access key assigned in source. Rotate the key in IAM and read it from the environment or a secret manager.',
  },
  {
    id: 'NPS-0101',
    rule_name: 'aws_session_token',
    category: 'cloud-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: assigned(
      keyword([ci('aws'), ci('session'), ci('token')]),
      '[A-Za-z0-9/+=]{100,}',
    ),
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'AWS STS session token committed to source. Session tokens are live until they expire; revoke the session and inject it at runtime.',
  },
  {
    id: 'NPS-0102',
    rule_name: 'gcp_service_account_private_key',
    category: 'cloud-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '"private_key"\\s*:\\s*"-----BEGIN [A-Z ]{0,20}PRIVATE KEY',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'GCP service-account JSON with embedded private key. Delete the key in IAM and use workload identity or a mounted secret.',
  },
  {
    id: 'NPS-0103',
    rule_name: 'gcp_service_account_json',
    category: 'cloud-credential',
    severity: 'high',
    cwe: [UNPROTECTED],
    regex: '"type"\\s*:\\s*"service_account"',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'GCP service-account key file checked in. Keep service-account JSON out of the repository entirely.',
  },
  {
    id: 'NPS-0104',
    rule_name: 'gcp_api_key',
    category: 'cloud-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bAIza[0-9A-Za-z_\\-]{35}(?![0-9A-Za-z_\\-])',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Google API key in source. Restrict the key by API and referrer, then rotate it and load it from configuration.',
  },
  {
    id: 'NPS-0105',
    rule_name: 'google_oauth_client_secret',
    category: 'cloud-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\bGOCSPX-[A-Za-z0-9_\\-]{28}(?![A-Za-z0-9_\\-])',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Google OAuth client secret in source. Reset the secret in the Google Cloud console and store it server-side only.',
  },
  {
    id: 'NPS-0106',
    rule_name: 'google_oauth_refresh_token',
    category: 'cloud-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\b1//0[A-Za-z0-9_\\-]{40,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Google OAuth refresh token in source. Refresh tokens do not expire on their own; revoke it and keep tokens in a secret store.',
  },
  {
    id: 'NPS-0107',
    rule_name: 'azure_storage_account_key',
    category: 'cloud-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: 'AccountKey=[A-Za-z0-9+/]{86}==',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Azure storage account key in source. Rotate both account keys and move to SAS tokens or managed identity.',
  },
  {
    id: 'NPS-0108',
    rule_name: 'azure_storage_connection_string',
    category: 'cloud-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: 'DefaultEndpointsProtocol=[a-z]{4,5};AccountName=[a-z0-9]{3,24};',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Azure storage connection string in source. Rotate the account keys and resolve the connection string from app configuration.',
  },
  {
    id: 'NPS-0109',
    rule_name: 'azure_ad_client_secret',
    category: 'cloud-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\b[A-Za-z0-9_~.\\-]{3}8Q~[A-Za-z0-9_~.\\-]{31,34}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Azure AD application client secret in source. Delete the secret in the app registration and prefer federated credentials.',
  },
  {
    id: 'NPS-0110',
    rule_name: 'github_pat_classic',
    category: 'vcs-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\bghp_[A-Za-z0-9]{36}\\b',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Classic GitHub personal access token in source. Revoke it in developer settings and use a short-lived app token.',
  },
  {
    id: 'NPS-0111',
    rule_name: 'github_pat_fine_grained',
    category: 'vcs-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\bgithub_pat_[A-Za-z0-9]{22}_[A-Za-z0-9]{59}\\b',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Fine-grained GitHub personal access token in source. Revoke it in developer settings and inject it from CI secrets.',
  },
  {
    id: 'NPS-0112',
    rule_name: 'github_oauth_access_token',
    category: 'vcs-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bgho_[A-Za-z0-9]{36}\\b',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'GitHub OAuth access token in source. Revoke the authorization and keep user tokens in server-side session storage.',
  },
  {
    id: 'NPS-0113',
    rule_name: 'github_app_installation_token',
    category: 'vcs-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bgh[us]_[A-Za-z0-9]{36}\\b',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'GitHub App user or installation token in source. These are short-lived but still live; mint them at runtime from the app private key.',
  },
  {
    id: 'NPS-0114',
    rule_name: 'github_refresh_token',
    category: 'vcs-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bghr_[A-Za-z0-9]{36}\\b',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'GitHub refresh token in source. Revoke the authorization; refresh tokens let an attacker mint new access tokens.',
  },
  {
    id: 'NPS-0115',
    rule_name: 'gitlab_personal_access_token',
    category: 'vcs-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\bglpat-[A-Za-z0-9_\\-]{20}(?![A-Za-z0-9_\\-])',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'GitLab personal access token in source. Revoke it in user settings and use a project or group access token with a short expiry.',
  },
  {
    id: 'NPS-0116',
    rule_name: 'gitlab_pipeline_trigger_token',
    category: 'vcs-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bglptt-[0-9a-f]{40}\\b',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'GitLab pipeline trigger token in source. Revoke it in the project CI settings; it can start pipelines on protected branches.',
  },
  {
    id: 'NPS-0117',
    rule_name: 'gitlab_runner_registration_token',
    category: 'vcs-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bGR1348941[A-Za-z0-9_\\-]{20}(?![A-Za-z0-9_\\-])',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'GitLab runner registration token in source. Reset it; anyone holding it can register a runner and read job secrets.',
  },
  {
    id: 'NPS-0118',
    rule_name: 'slack_bot_token',
    category: 'saas-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\bxoxb-[0-9]{10,14}-[0-9]{10,14}-[A-Za-z0-9]{20,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Slack bot token in source. Rotate it in the app credentials page and read it from the environment.',
  },
  {
    id: 'NPS-0119',
    rule_name: 'slack_user_token',
    category: 'saas-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\bxoxp-[0-9]{8,}-[0-9A-Za-z\\-]{20,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Slack user token in source. It acts as the user; revoke the app authorization and rotate the token.',
  },
  {
    id: 'NPS-0120',
    rule_name: 'slack_legacy_workspace_token',
    category: 'saas-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bxox[as]-[0-9]{1,}-[0-9A-Za-z\\-]{20,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Legacy Slack workspace or app token in source. Migrate to a granular bot token and revoke the legacy one.',
  },
  {
    id: 'NPS-0121',
    rule_name: 'slack_incoming_webhook_url',
    category: 'saas-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: 'https://hooks\\.slack\\.com/services/T[A-Z0-9]{8,}/B[A-Z0-9]{8,}/[A-Za-z0-9]{20,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Slack incoming webhook URL in source. The URL is the credential; regenerate the webhook and store it as a secret.',
  },
  {
    id: 'NPS-0122',
    rule_name: 'stripe_live_restricted_key',
    category: 'payment-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\brk_live_[A-Za-z0-9]{20,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Live Stripe restricted key in source. Roll the key in the Stripe dashboard and load it from a secret manager.',
  },
  {
    id: 'NPS-0123',
    rule_name: 'stripe_webhook_signing_secret',
    category: 'payment-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bwhsec_[A-Za-z0-9]{28,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Stripe webhook signing secret in source. Anyone with it can forge webhook events; roll the endpoint secret.',
  },
  {
    id: 'NPS-0124',
    rule_name: 'stripe_test_secret_key',
    category: 'payment-credential',
    severity: 'low',
    cwe: [HARDCODED],
    regex: '\\bsk_test_[A-Za-z0-9]{20,}',
    exclude_paths: GENERIC_EXCLUDE_PATHS,
    reminder: 'Stripe test-mode secret key in source. Test keys touch no real money, but keeping them out of the repo avoids habit drift.',
  },
  {
    id: 'NPS-0125',
    rule_name: 'stripe_test_publishable_key',
    category: 'payment-credential',
    severity: 'low',
    cwe: [HARDCODED],
    regex: '\\bpk_test_[A-Za-z0-9]{20,}',
    exclude_paths: GENERIC_EXCLUDE_PATHS,
    reminder: 'Stripe test-mode publishable key in source. Publishable test keys are safe to expose; move it to config for consistency.',
  },
  {
    id: 'NPS-0126',
    rule_name: 'twilio_api_key_sid',
    category: 'saas-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bSK[0-9a-f]{32}\\b',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Twilio API key SID in source. Delete the API key in the Twilio console; its secret half is likely nearby.',
  },
  {
    id: 'NPS-0127',
    rule_name: 'twilio_account_sid',
    category: 'saas-credential',
    severity: 'medium',
    cwe: [UNPROTECTED],
    regex: '\\bAC[0-9a-f]{32}\\b',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Twilio account SID in source. The SID is the username half of the API credential pair; check whether the auth token leaked with it.',
  },
  {
    id: 'NPS-0128',
    rule_name: 'twilio_auth_token',
    category: 'saas-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: assigned(
      keyword([ci('twilio'), optional(ci('auth')) + ci('token')]),
      '[0-9a-f]{32}\\b',
    ),
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Twilio auth token in source. Rotate the token in the console; it grants full account access including billing.',
  },
  {
    id: 'NPS-0129',
    rule_name: 'sendgrid_api_key',
    category: 'saas-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\bSG\\.[A-Za-z0-9_\\-]{22}\\.[A-Za-z0-9_\\-]{43}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'SendGrid API key in source. Delete the key in SendGrid settings; it can send mail as your domain.',
  },
  {
    id: 'NPS-0130',
    rule_name: 'mailgun_api_key',
    category: 'saas-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bkey-[0-9a-f]{32}\\b',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Mailgun private API key in source. Rotate it in the Mailgun dashboard and read it from the environment.',
  },
  {
    id: 'NPS-0131',
    rule_name: 'mailchimp_api_key',
    category: 'saas-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\b[0-9a-f]{32}-us[0-9]{1,2}\\b',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Mailchimp API key in source. Revoke it in account extras; it exposes your full audience list.',
  },
  {
    id: 'NPS-0132',
    rule_name: 'openai_api_key',
    category: 'ai-provider-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bsk-[A-Za-z0-9]{48}\\b',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'OpenAI API key in source. Revoke it in the API keys page; leaked keys are drained for credit within minutes.',
  },
  {
    id: 'NPS-0133',
    rule_name: 'openai_project_api_key',
    category: 'ai-provider-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bsk-proj-[A-Za-z0-9_\\-]{40,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'OpenAI project API key in source. Revoke it in the project settings and inject it from the environment.',
  },
  {
    id: 'NPS-0134',
    rule_name: 'anthropic_api_key',
    category: 'ai-provider-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\bsk-ant-[A-Za-z0-9]{2,}-[A-Za-z0-9_\\-]{80,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Anthropic API key in source. Revoke it in the console and read it from ANTHROPIC_API_KEY at runtime.',
  },
  {
    id: 'NPS-0135',
    rule_name: 'huggingface_access_token',
    category: 'ai-provider-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bhf_[A-Za-z0-9]{34,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Hugging Face access token in source. Revoke it in access tokens; write tokens can publish to your repos.',
  },
  {
    id: 'NPS-0136',
    rule_name: 'npm_access_token',
    category: 'registry-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\bnpm_[A-Za-z0-9]{36}\\b',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'npm access token in source. Revoke it on npmjs.com; a publish token allows shipping malicious versions of your packages.',
  },
  {
    id: 'NPS-0137',
    rule_name: 'npmrc_auth_token',
    category: 'config-credential',
    severity: 'high',
    cwe: [UNPROTECTED],
    regex: '_authToken\\s*=\\s*(?!\\$\\{)[^\\s]{8,}',
    paths: ['**/.npmrc'],
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Literal _authToken in a committed .npmrc. Reference an environment variable such as ${NPM_TOKEN} instead.',
  },
  {
    id: 'NPS-0138',
    rule_name: 'pypi_upload_token',
    category: 'registry-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\bpypi-AgEIcHlwaS5vcmc[A-Za-z0-9_\\-]{50,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'PyPI upload token in source. Revoke it in your PyPI account settings and use trusted publishing from CI.',
  },
  {
    id: 'NPS-0139',
    rule_name: 'pypirc_password',
    category: 'config-credential',
    severity: 'high',
    cwe: [UNPROTECTED],
    regex: keyword([ci('password')]) + '\\s*[:=]\\s*(?!\\$\\{)[^\\s]{8,}',
    paths: ['**/.pypirc'],
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Literal password in a committed .pypirc. Use an API token via environment variables or trusted publishing.',
  },
  {
    id: 'NPS-0140',
    rule_name: 'rubygems_api_key',
    category: 'registry-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\brubygems_[0-9a-f]{48}\\b',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'RubyGems API key in source. Reset it on rubygems.org; it can yank and publish gem versions.',
  },
  {
    id: 'NPS-0141',
    rule_name: 'dockerhub_personal_access_token',
    category: 'registry-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\bdckr_pat_[A-Za-z0-9_\\-]{20,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Docker Hub personal access token in source. Delete it in security settings; it can push tampered images to your repositories.',
  },
  {
    id: 'NPS-0142',
    rule_name: 'cloudflare_api_token',
    category: 'saas-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: assigned(
      keyword([anyOf([ci('cloudflare'), ci('cf')]), optional(ci('api')) + ci('token')]),
      '([A-Za-z0-9_\\-]{40})(?![A-Za-z0-9_\\-])',
    ),
    entropy: { minLength: 40 },
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Cloudflare API token in source. Roll the token in the dashboard and scope it to the zones it actually needs.',
  },
  {
    id: 'NPS-0143',
    rule_name: 'cloudflare_global_api_key',
    category: 'saas-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: assigned(
      keyword([anyOf([ci('cloudflare'), ci('cf')]), ci('api'), ci('key')]),
      '[0-9a-f]{37}(?![0-9a-f])',
    ),
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Cloudflare global API key in source. Rotate it and replace it with a scoped API token; the global key controls the whole account.',
  },
  {
    id: 'NPS-0144',
    rule_name: 'digitalocean_personal_access_token',
    category: 'saas-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\bdop_v1_[0-9a-f]{64}\\b',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'DigitalOcean personal access token in source. Revoke it in the API page; it can create and destroy droplets.',
  },
  {
    id: 'NPS-0145',
    rule_name: 'digitalocean_oauth_token',
    category: 'saas-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bdo[or]_v1_[0-9a-f]{64}\\b',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'DigitalOcean OAuth access or refresh token in source. Revoke the grant and keep tokens in server-side storage.',
  },
  {
    id: 'NPS-0146',
    rule_name: 'heroku_api_key',
    category: 'saas-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: assigned(
      keyword([ci('heroku'), optional(ci('api')) + ci('key')]),
      '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}',
    ),
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Heroku API key in source. Regenerate it with heroku authorizations:revoke and use a short-lived authorization instead.',
  },
  {
    id: 'NPS-0147',
    rule_name: 'datadog_api_or_app_key',
    category: 'saas-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: assigned(
      keyword([anyOf([ci('datadog'), ci('dd')]), anyOf([ci('application'), ci('api'), ci('app')]), ci('key')]),
      '([0-9a-f]{32,40})(?![0-9a-f])',
    ),
    entropy: { minLength: 32 },
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Datadog API or application key in source. Revoke it in organization settings and inject it through the agent configuration.',
  },
  {
    id: 'NPS-0148',
    rule_name: 'newrelic_user_api_key',
    category: 'saas-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bNRAK-[A-Z0-9]{27}\\b',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'New Relic user API key in source. Delete it in API keys; it can read and modify account configuration.',
  },
  {
    id: 'NPS-0149',
    rule_name: 'newrelic_ingest_license_key',
    category: 'saas-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\b[0-9a-f]{36}NRAL\\b',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'New Relic ingest license key in source. Rotate it; it lets anyone write telemetry into your account.',
  },
  {
    id: 'NPS-0150',
    rule_name: 'sentry_auth_token',
    category: 'saas-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bsntry[su]_[A-Za-z0-9_.\\-]{40,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Sentry auth token in source. Revoke it in Sentry settings; it can read issues and upload source maps.',
  },
  {
    id: 'NPS-0151',
    rule_name: 'sentry_dsn',
    category: 'saas-credential',
    severity: 'medium',
    cwe: [UNPROTECTED],
    regex: 'https://[0-9a-f]{32}(?::[0-9a-f]{32})?@[A-Za-z0-9.\\-]{0,60}sentry\\.io/[0-9]{1,10}',
    exclude_paths: GENERIC_EXCLUDE_PATHS,
    reminder: 'Sentry DSN in source. A client DSN is semi-public, but a DSN with a secret half must be rotated and kept server-side.',
  },
  {
    id: 'NPS-0152',
    rule_name: 'algolia_admin_api_key',
    category: 'saas-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: assigned(
      keyword([ci('algolia'), anyOf([ci('admin'), ci('api')]), ci('key')]),
      '([0-9a-f]{32})(?![0-9a-f])',
    ),
    entropy: { minLength: 32 },
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Algolia admin API key in source. Regenerate it and ship only the search-only key to clients.',
  },
  {
    id: 'NPS-0153',
    rule_name: 'firebase_cloud_messaging_key',
    category: 'saas-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bAAAA[A-Za-z0-9_\\-]{7}:APA91b[A-Za-z0-9_\\-]{100,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Firebase Cloud Messaging server key in source. Rotate it in the Firebase console; it can push notifications to every install.',
  },
  {
    id: 'NPS-0154',
    rule_name: 'supabase_service_role_key',
    category: 'saas-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: keyword([ci('service'), ci('role')])
      + '[^\\n]{0,40}eyJ[A-Za-z0-9_\\-]{10,}\\.eyJ[A-Za-z0-9_\\-]{10,}\\.[A-Za-z0-9_\\-]{10,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Supabase service-role JWT in source. It bypasses row-level security; rotate the JWT secret and keep it server-side only.',
  },
  {
    id: 'NPS-0155',
    rule_name: 'supabase_personal_access_token',
    category: 'saas-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\bsbp_[0-9a-f]{40}\\b',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Supabase personal access token in source. Revoke it in account settings; it controls every project you can access.',
  },
  {
    id: 'NPS-0156',
    rule_name: 'supabase_secret_key',
    category: 'saas-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\bsb_secret_[A-Za-z0-9_\\-]{20,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Supabase secret API key in source. Revoke it in project API settings and use the publishable key on clients.',
  },
  {
    id: 'NPS-0157',
    rule_name: 'postgres_uri_with_password',
    category: 'database-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bpostgres(?:ql)?://[^:@/\\s]{1,64}:(?!\\$)[^@/\\s]{3,}@[A-Za-z0-9._\\-]{3,}',
    exclude_paths: GENERIC_EXCLUDE_PATHS,
    reminder: 'PostgreSQL connection URI with an inline password. Rotate the role password and assemble the URI from environment variables.',
  },
  {
    id: 'NPS-0158',
    rule_name: 'mysql_uri_with_password',
    category: 'database-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bmysql://[^:@/\\s]{1,64}:(?!\\$)[^@/\\s]{3,}@[A-Za-z0-9._\\-]{3,}',
    exclude_paths: GENERIC_EXCLUDE_PATHS,
    reminder: 'MySQL connection URI with an inline password. Rotate the user password and read the URI from configuration.',
  },
  {
    id: 'NPS-0159',
    rule_name: 'mongodb_uri_with_password',
    category: 'database-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bmongodb(?:\\+srv)?://[^:@/\\s]{1,64}:(?!\\$)[^@/\\s]{3,}@[A-Za-z0-9._\\-]{3,}',
    exclude_paths: GENERIC_EXCLUDE_PATHS,
    reminder: 'MongoDB connection URI with an inline password. Rotate the database user and inject the URI at runtime.',
  },
  {
    id: 'NPS-0160',
    rule_name: 'redis_uri_with_password',
    category: 'database-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\brediss?://[^:@/\\s]{0,64}:(?!\\$)[^@/\\s]{3,}@[A-Za-z0-9._\\-]{3,}',
    exclude_paths: GENERIC_EXCLUDE_PATHS,
    reminder: 'Redis connection URI with an inline password. Rotate the Redis auth password and read the URI from configuration.',
  },
  {
    id: 'NPS-0161',
    rule_name: 'amqp_uri_with_password',
    category: 'database-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bamqps?://[^:@/\\s]{1,64}:(?!\\$)[^@/\\s]{3,}@[A-Za-z0-9._\\-]{3,}',
    exclude_paths: GENERIC_EXCLUDE_PATHS,
    reminder: 'AMQP connection URI with an inline password. Rotate the broker user and build the URI from environment variables.',
  },
  {
    id: 'NPS-0162',
    rule_name: 'jwt_with_payload',
    category: 'generic-credential',
    severity: 'medium',
    cwe: [HARDCODED],
    regex: '\\beyJ[A-Za-z0-9_\\-]{10,}\\.eyJ[A-Za-z0-9_\\-]{10,}\\.[A-Za-z0-9_\\-]{10,}',
    exclude_paths: GENERIC_EXCLUDE_PATHS,
    reminder: 'Signed JWT with a non-empty payload in source. Treat it as a live bearer credential: decode it, confirm the audience, and rotate the signing key.',
  },
  {
    id: 'NPS-0163',
    rule_name: 'pgp_private_key_block',
    category: 'private-key',
    severity: 'critical',
    cwe: [HARDCODED],
    substrings: ['-----BEGIN PGP PRIVATE KEY BLOCK-----'],
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'PGP private key block in source. Revoke the key, publish the revocation certificate, and keep private keys in a hardware token or keyring.',
  },
  {
    id: 'NPS-0164',
    rule_name: 'ssh_encrypted_private_key_block',
    category: 'private-key',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '-----BEGIN (?:SSH2 |ENCRYPTED |SSH2 ENCRYPTED )PRIVATE KEY-----',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Encrypted SSH private key block in source. A passphrase only buys time; remove the key from history and rotate the keypair.',
  },
  {
    id: 'NPS-0165',
    rule_name: 'putty_private_key_file',
    category: 'private-key',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: 'PuTTY-User-Key-File-[0-9]:\\s*(?:ssh-rsa|ssh-dss|ssh-ed25519|ecdsa-sha2)',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'PuTTY private key (.ppk) committed to the repository. Rotate the keypair and store .ppk files outside version control.',
  },
  {
    id: 'NPS-0166',
    rule_name: 'openssh_private_key_body',
    category: 'private-key',
    severity: 'critical',
    cwe: [HARDCODED],
    substrings: ['b3BlbnNzaC1rZXktdjE'],
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Base64 body of an OpenSSH private key, even with the PEM header stripped. Rotate the keypair and purge it from history.',
  },
  {
    id: 'NPS-0167',
    rule_name: 'kubernetes_service_account_token',
    category: 'infrastructure-credential',
    severity: 'high',
    cwe: [UNPROTECTED],
    regex: 'kubernetes\\.io/service-account-token',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Kubernetes service-account token secret in a committed manifest. Use projected, short-lived tokens and never commit the token value.',
  },
  {
    id: 'NPS-0168',
    rule_name: 'terraform_cloud_api_token',
    category: 'infrastructure-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\b[A-Za-z0-9]{14}\\.atlasv1\\.[A-Za-z0-9_\\-]{40,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Terraform Cloud API token in source. Revoke it in the organization tokens page; it can plan and apply against your infrastructure.',
  },
  {
    id: 'NPS-0169',
    rule_name: 'vault_service_token',
    category: 'infrastructure-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\bhvs\\.[A-Za-z0-9_\\-]{24,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'HashiCorp Vault service token in source. Revoke it with vault token revoke and use an auth method instead of a static token.',
  },
  {
    id: 'NPS-0170',
    rule_name: 'vault_batch_token',
    category: 'infrastructure-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bhvb\\.[A-Za-z0-9_\\-]{24,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'HashiCorp Vault batch token in source. Batch tokens cannot be revoked individually; rotate the underlying role and shorten its TTL.',
  },
  {
    id: 'NPS-0171',
    rule_name: 'vault_legacy_token',
    category: 'infrastructure-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '(?:^|[\\s"\'=:,\\[])s\\.[A-Za-z0-9]{24}(?![A-Za-z0-9])',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Legacy HashiCorp Vault token (s. prefix) in source. Revoke it and migrate to the current service-token format.',
  },
  {
    id: 'NPS-0172',
    rule_name: 'shopify_access_token',
    category: 'saas-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\bshpat_[0-9a-fA-F]{32}\\b',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Shopify admin API access token in source. Uninstall or rotate the app credential; it can read orders and customer data.',
  },
  {
    id: 'NPS-0173',
    rule_name: 'shopify_shared_secret',
    category: 'saas-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\bshpss_[0-9a-fA-F]{32}\\b',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Shopify app shared secret in source. Rotate it; it verifies webhook authenticity and OAuth callbacks.',
  },
  {
    id: 'NPS-0174',
    rule_name: 'shopify_app_token',
    category: 'saas-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bshp(?:ca|pa)_[0-9a-fA-F]{32}\\b',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Shopify custom or private app token in source. Rotate the credential in the Shopify admin.',
  },
  {
    id: 'NPS-0175',
    rule_name: 'square_access_token',
    category: 'payment-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\bsq0atp-[A-Za-z0-9_\\-]{22}(?![A-Za-z0-9_\\-])',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Square production access token in source. Rotate it in the developer dashboard; it can move money.',
  },
  {
    id: 'NPS-0176',
    rule_name: 'square_oauth_client_secret',
    category: 'payment-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\bsq0csp-[A-Za-z0-9_\\-]{43}(?![A-Za-z0-9_\\-])',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Square OAuth application secret in source. Rotate it in the developer dashboard and keep it on the server only.',
  },
  {
    id: 'NPS-0177',
    rule_name: 'braintree_production_access_token',
    category: 'payment-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\baccess_token\\$production\\$[0-9a-z]{16}\\$[0-9a-f]{32}\\b',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Braintree production access token in source. Revoke it in the Braintree control panel; it authorizes live transactions.',
  },
  {
    id: 'NPS-0178',
    rule_name: 'braintree_sandbox_access_token',
    category: 'payment-credential',
    severity: 'low',
    cwe: [HARDCODED],
    regex: '\\baccess_token\\$sandbox\\$[0-9a-z]{16}\\$[0-9a-f]{32}\\b',
    exclude_paths: GENERIC_EXCLUDE_PATHS,
    reminder: 'Braintree sandbox access token in source. Sandbox credentials move no real money; still prefer loading them from configuration.',
  },
  {
    id: 'NPS-0179',
    rule_name: 'paypal_client_secret',
    category: 'payment-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: assigned(
      keyword([ci('paypal'), optional(ci('client')) + ci('secret')]),
      '([A-Za-z0-9_\\-]{40,})(?![A-Za-z0-9_\\-])',
    ),
    entropy: { minLength: 40 },
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'PayPal REST application client secret in source. Rotate it in the developer dashboard and keep it server-side.',
  },
  {
    id: 'NPS-0180',
    rule_name: 'atlassian_api_token',
    category: 'saas-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bATATT3x[A-Za-z0-9_\\-=]{100,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Atlassian (Jira/Confluence) API token in source. Revoke it in account security settings; it acts as the whole user.',
  },
  {
    id: 'NPS-0181',
    rule_name: 'netlify_access_token',
    category: 'saas-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bnfp_[A-Za-z0-9_\\-]{30,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Netlify personal access token in source. Revoke it in user applications; it can deploy to every site you own.',
  },
  {
    id: 'NPS-0182',
    rule_name: 'vercel_access_token',
    category: 'saas-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: assigned(
      keyword([ci('vercel'), optional(ci('api')) + ci('token')]),
      '([A-Za-z0-9]{24})(?![A-Za-z0-9])',
    ),
    entropy: { minLength: 24 },
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Vercel access token in source. Revoke it in account tokens; it can deploy and read environment variables.',
  },
  {
    id: 'NPS-0183',
    rule_name: 'linear_api_key',
    category: 'saas-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\blin_(?:api|oauth)_[A-Za-z0-9]{40,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Linear API key in source. Revoke it in Linear API settings and use OAuth with narrow scopes.',
  },
  {
    id: 'NPS-0184',
    rule_name: 'notion_integration_token',
    category: 'saas-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\b(?:secret_[A-Za-z0-9]{43}|ntn_[A-Za-z0-9]{40,})(?![A-Za-z0-9])',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Notion integration token in source. Rotate it in the integration settings; it reads every page shared with the integration.',
  },
  {
    id: 'NPS-0185',
    rule_name: 'discord_bot_token',
    category: 'saas-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\b[MNO][A-Za-z0-9_\\-]{23,25}\\.[A-Za-z0-9_\\-]{6}\\.[A-Za-z0-9_\\-]{27,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Discord bot token in source. Regenerate it in the developer portal; the token is full control of the bot account.',
  },
  {
    id: 'NPS-0186',
    rule_name: 'discord_webhook_url',
    category: 'saas-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: 'https://discord(?:app)?\\.com/api/webhooks/[0-9]{17,20}/[A-Za-z0-9_\\-]{50,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Discord webhook URL in source. The URL is the credential; delete the webhook and store the replacement as a secret.',
  },
  {
    id: 'NPS-0187',
    rule_name: 'telegram_bot_token',
    category: 'saas-credential',
    severity: 'critical',
    cwe: [HARDCODED],
    regex: '\\b[0-9]{8,10}:AA[A-Za-z0-9_\\-]{32,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Telegram bot token in source. Revoke it with BotFather; the token can read and send every bot message.',
  },
  {
    id: 'NPS-0188',
    rule_name: 'twitter_bearer_token',
    category: 'saas-credential',
    severity: 'high',
    cwe: [HARDCODED],
    regex: '\\bAAAAAAAAAAAAAAAAAAAAA[A-Za-z0-9%]{35,}',
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Twitter/X app-only bearer token in source. Regenerate it in the developer portal and keep it server-side.',
  },
  {
    id: 'NPS-0189',
    rule_name: 'basic_auth_credentials_in_url',
    category: 'generic-credential',
    severity: 'medium',
    cwe: [UNPROTECTED],
    regex: '\\bhttps?://[A-Za-z0-9._%\\-]{2,64}:(?!\\$)[^@/\\s]{4,}@[A-Za-z0-9.\\-]{3,}',
    exclude_paths: GENERIC_EXCLUDE_PATHS,
    reminder: 'HTTP basic-auth credentials embedded in a URL. URLs leak through logs, proxies and referrers; pass credentials in a header instead.',
  },
  {
    id: 'NPS-0190',
    rule_name: 'bearer_token_literal',
    category: 'generic-credential',
    severity: 'medium',
    cwe: [HARDCODED],
    regex: '[Bb]earer\\s+([A-Za-z0-9_\\-.=+/]{30,})(?![A-Za-z0-9_\\-.=+/])',
    entropy: { minLength: 30 },
    exclude_paths: GENERIC_EXCLUDE_PATHS,
    reminder: 'Literal bearer token in an Authorization value. Read the token from configuration and rotate whatever issued it.',
  },
  {
    id: 'NPS-0191',
    rule_name: 'basic_authorization_header',
    category: 'generic-credential',
    severity: 'medium',
    cwe: [UNPROTECTED],
    regex: keyword([ci('authorization')]) + '["\']?\\s*[:=]\\s*["\']?Basic\\s+[A-Za-z0-9+/=]{16,}',
    exclude_paths: GENERIC_EXCLUDE_PATHS,
    reminder: 'Hardcoded basic Authorization header. Base64 is not encryption; move the credential pair into configuration.',
  },
  {
    id: 'NPS-0192',
    rule_name: 'dotenv_secret_assignment',
    category: 'config-credential',
    severity: 'medium',
    cwe: [UNPROTECTED],
    regex: '[A-Z0-9_]{0,40}'
      + anyOf(['SECRET', 'TOKEN', 'PASSWORD', 'PASSWD', 'API_KEY', 'APIKEY', 'PRIVATE_KEY', 'ACCESS_KEY'])
      + '[A-Z0-9_]{0,20}\\s*=\\s*(?!\\$)[^\\s#]{8,}',
    paths: ['**/.env', '**/.env.*'],
    exclude_paths: FIXTURE_EXCLUDE_PATHS,
    reminder: 'Literal credential in a committed .env file. Commit only .env.example with placeholder values and keep real values out of git.',
  },
  {
    id: 'NPS-0193',
    rule_name: 'bcrypt_password_hash',
    category: 'generic-credential',
    severity: 'medium',
    cwe: [UNPROTECTED],
    regex: '\\$2[aby]?\\$[0-9]{2}\\$[A-Za-z0-9./]{53}',
    exclude_paths: GENERIC_EXCLUDE_PATHS,
    reminder: 'bcrypt password hash in source. Hashes are offline-crackable; keep credential material in the database, not in the repository.',
  },
  {
    id: 'NPS-0194',
    rule_name: 'high_entropy_secret_assignment',
    category: 'generic-credential',
    severity: 'medium',
    cwe: [HARDCODED],
    regex: anyOf([
      ci('secret'), ci('token'), ci('password'), ci('passwd'), ci('apikey'),
      ci('api_key'), ci('access_key'), ci('private_key'), ci('credential'),
    ]) + '["\']?\\s*(?:[:=]|=>)\\s*["\']([A-Za-z0-9+/=_\\-]{24,})["\']',
    entropy: { minLength: 24 },
    exclude_paths: GENERIC_EXCLUDE_PATHS,
    reminder: 'A credential-named variable assigned a high-entropy literal. Confirm whether it is a live secret, then move it into a secret manager.',
  },
];

function _freeze(rules) {
  for (const rule of rules) {
    for (const key of ['cwe', 'paths', 'exclude_paths', 'substrings']) {
      if (Array.isArray(rule[key])) Object.freeze(rule[key]);
    }
    if (rule.entropy) Object.freeze(rule.entropy);
    Object.freeze(rule);
  }
  return Object.freeze(rules);
}

const SECRET_RULES = _freeze(RULES);

module.exports = {
  SECRET_RULES,
  FIXTURE_EXCLUDE_PATHS,
  GENERIC_EXCLUDE_PATHS,
  ci,
};
