'use strict';

const { test } = require('node:test');
const assert = require('node:assert/strict');

const { FILES, parse } = require('./cargo.cjs');

const REGISTRY = 'registry+https://github.com/rust-lang/crates.io-index';

test('CARGO-1 lockfile version 3 yields registry packages as indirect prod entries', () => {
  const content = [
    '# This file is automatically @generated by Cargo.',
    '# It is not intended for manual editing.',
    'version = 3',
    '',
    '[[package]]',
    'name = "serde"',
    'version = "1.0.197"',
    'source = "' + REGISTRY + '"',
    'checksum = "3fb1c873e1b9b056a4dc4c0c198b24c3ffa059243875552b2bd0933b1aee4ce2"',
    'dependencies = [',
    ' "serde_derive",',
    ']',
    '',
    '[[package]]',
    'name = "serde_json"',
    'version = "1.0.114"',
    'source = "' + REGISTRY + '"',
    'checksum = "c5f09b1bd632ef549eaa9f60a1f8de742bdbc698e6cee2095fc84dde5f549ae0"',
    '',
  ].join('\n');

  const { packages, warnings } = parse(content, { file: 'Cargo.lock' });

  assert.deepEqual(warnings, []);
  assert.deepEqual(packages.map((p) => p.purl), [
    'pkg:cargo/serde@1.0.197',
    'pkg:cargo/serde_json@1.0.114',
  ]);
  assert.equal(packages[1].key, 'serde-json');
  for (const pkg of packages) {
    assert.equal(pkg.ecosystem, 'crates.io');
    assert.equal(pkg.scope, 'prod');
    assert.equal(pkg.direct, false);
    assert.equal(pkg.source, 'Cargo.lock');
  }
});

test('CARGO-2 a package without a source is a workspace member and is skipped with a warning', () => {
  const content = [
    'version = 4',
    '',
    '[[package]]',
    'name = "my-app"',
    'version = "0.1.0"',
    'dependencies = [',
    ' "anyhow",',
    ']',
    '',
    '[[package]]',
    'name = "my-app-core"',
    'version = "0.1.0"',
    '',
    '[[package]]',
    'name = "anyhow"',
    'version = "1.0.80"',
    'source = "' + REGISTRY + '"',
    'checksum = "5ad32ce52e4161730f7098c077cd2ed6229b5804ccf99e5366be1ab72a98b4e1"',
    '',
  ].join('\n');

  const { packages, warnings } = parse(content, { file: 'crates/Cargo.lock' });

  assert.deepEqual(packages.map((p) => p.purl), ['pkg:cargo/anyhow@1.0.80']);
  assert.deepEqual(warnings, ['workspace-member']);
  assert.equal(packages[0].source, 'crates/Cargo.lock');
});

test('CARGO-3 the versionless legacy format parses the same way', () => {
  const content = [
    '[root]',
    'name = "legacy-app"',
    'version = "0.0.1"',
    'dependencies = [',
    ' "libc 0.2.153 (registry+https://github.com/rust-lang/crates.io-index)",',
    ']',
    '',
    '[[package]]',
    'name = "libc"',
    'version = "0.2.153"',
    'source = "' + REGISTRY + '"',
    '',
    '[metadata]',
    '"checksum libc 0.2.153" = "9c198f91728a82281a64e1f4f9eeb25d82cb32a5de251c6bd1b5154d63a8e7bd"',
    '',
  ].join('\n');

  const { packages, warnings } = parse(content, { file: 'Cargo.lock' });

  assert.deepEqual(warnings, []);
  assert.deepEqual(packages.map((p) => p.purl), ['pkg:cargo/libc@0.2.153']);
  assert.equal(packages[0].version, '0.2.153');
});

test('CARGO-4 a package missing its version still lands with a null version and a warning', () => {
  const content = [
    '[[package]]',
    'name = "half-entry"',
    'source = "' + REGISTRY + '"',
    '',
  ].join('\n');

  const { packages, warnings } = parse(content, { file: 'Cargo.lock' });

  assert.equal(packages.length, 1);
  assert.equal(packages[0].version, null);
  assert.equal(packages[0].purl, 'pkg:cargo/half-entry');
  assert.deepEqual(warnings, ['missing-version']);
});

test('CARGO-5 unknown basename reports unsupported-file', () => {
  assert.deepEqual(parse('anything', { file: 'Cargo.toml' }), { packages: [], warnings: ['unsupported-file'] });
  assert.deepEqual(parse('anything', {}), { packages: [], warnings: ['unsupported-file'] });
});

test('CARGO-6 malformed input warns instead of throwing', () => {
  const garbage = parse('this is not toml at all {{{ ][', { file: 'Cargo.lock' });
  assert.deepEqual(garbage, { packages: [], warnings: ['no-packages'] });

  const nameless = parse([
    '[[package]]',
    'version = "1.0.0"',
    'source = "' + REGISTRY + '"',
    '',
    '[[package]]',
    'name = "good"',
    'version = "2.0.0"',
    'source = "' + REGISTRY + '"',
  ].join('\n'), { file: 'Cargo.lock' });

  assert.deepEqual(nameless.packages.map((p) => p.purl), ['pkg:cargo/good@2.0.0']);
  assert.deepEqual(nameless.warnings, ['malformed-package']);

  assert.deepEqual(parse(undefined, { file: 'Cargo.lock' }), { packages: [], warnings: ['no-packages'] });
});

test('CARGO-7 FILES is a frozen list of the handled basenames', () => {
  assert.deepEqual([...FILES], ['Cargo.lock']);
  assert.equal(Object.isFrozen(FILES), true);
});
