'use strict';

// Roadmap graph rendering (ADR-0027).
//
// roadmap.yaml already encodes a dependency graph — milestones carry depends_on
// (ADR-0006), slices run as serial waves inside a milestone, and tasks carry
// their own depends_on in the plan frontmatter — but every existing view of it is
// a list. `roadmap-render` produces a table; `dashboard` produces a status block;
// `stats` produces counters. A reader who wants to know "what unblocks when this
// slice lands" has to reconstruct the edges by hand.
//
// This renders the graph as text, in two formats a reader already has a viewer
// for: Mermaid (renders inline in the VitePress docs and in most Markdown
// previewers) and Graphviz DOT (for anyone who wants layout control).
//
// Read-only, and deliberately so. The lesson taken from the visual-builder tools
// is narrow: a diagram is a good *view* of a plan. It is not a good editor for
// one, because the plan's source of truth is a reviewable text file under git,
// and a drag-and-drop surface that writes back to it would trade that for a
// binary-ish blob nobody can diff. So there is no write path here, and the
// generated block carries a do-not-edit header.

const { NubosPilotError } = require('./core.cjs');
const conditions = require('./slice-conditions.cjs');

const FORMATS = Object.freeze(['mermaid', 'dot']);

const LEVELS = Object.freeze(['milestone', 'slice', 'task']);

// Status → a class name shared by both renderers. Grouping the many milestone
// statuses into four buckets keeps the legend readable: the diagram answers
// "what is blocked", not "what is the exact enum value", and roadmap-render
// already prints the latter.
const STATUS_CLASSES = Object.freeze({
  done: 'done',
  complete: 'done',
  verified: 'done',
  'in-progress': 'active',
  pending: 'pending',
  backlog: 'pending',
  parked: 'pending',
  skipped: 'skipped',
  failed: 'failed',
  deferred: 'skipped',
});

const CLASS_STYLE = Object.freeze({
  // Colour pairs chosen to stay legible on both light and dark Markdown themes,
  // and distinguishable when printed greyscale (the fill lightness differs).
  done:    { fill: '#d5f5e3', stroke: '#1e8449', font: '#0b3d20' },
  active:  { fill: '#d6eaf8', stroke: '#1f618d', font: '#0a2d43' },
  pending: { fill: '#f4f6f7', stroke: '#7f8c8d', font: '#2c3e50' },
  skipped: { fill: '#fdebd0', stroke: '#b9770e', font: '#4d3308' },
  failed:  { fill: '#fadbd8', stroke: '#a93226', font: '#4d1512' },
});

const GENERATED_HEADER = 'Generated by `np-tools.cjs roadmap-graph` — do not edit by hand.';

function _err(code, message, details) {
  return new NubosPilotError(code, message, details || {});
}

function statusClass(status) {
  const s = typeof status === 'string' ? status.toLowerCase() : '';
  return STATUS_CLASSES[s] || 'pending';
}

/**
 * Mermaid node ids must be identifier-ish, and a raw milestone/slice/task id is
 * close but not guaranteed. Normalise rather than trust.
 */
function nodeId(prefix, rawId) {
  return prefix + '_' + String(rawId).replace(/[^A-Za-z0-9]/g, '_');
}

/**
 * Compose a child key under its parent without repeating a prefix the child
 * already carries.
 *
 * Callers hand us either local ids (`S001`, from a raw roadmap node) or fully
 * qualified ones (`M001-S001`, from lib/planning-tree.cjs). Blindly
 * concatenating produced `M001_M001_S001` for the qualified case — unique, but
 * unreadable in a diagram whose whole purpose is being read.
 */
function _qualify(parentKey, childId) {
  const child = String(childId);
  return child.startsWith(parentKey) ? child : parentKey + '_' + child;
}

/**
 * Escape a label for a Mermaid node. Mermaid takes the label inside brackets, so
 * a bracket or quote in a milestone name breaks the diagram — which is why this
 * is not "probably fine": a plan named `Auth [phase 2]` would emit a parse error
 * rather than a diagram, and the failure surfaces in the docs build, far away.
 */
function escapeMermaid(text) {
  return String(text == null ? '' : text)
    .replace(/["]/g, '&quot;')
    .replace(/[[\]{}()]/g, (ch) => ({
      '[': '&#91;', ']': '&#93;', '{': '&#123;', '}': '&#125;', '(': '&#40;', ')': '&#41;',
    })[ch])
    .replace(/[<>]/g, (ch) => (ch === '<' ? '&lt;' : '&gt;'))
    .replace(/\|/g, '&#124;')
    .replace(/\r?\n/g, ' ')
    .trim();
}

function escapeDot(text) {
  return String(text == null ? '' : text)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r?\n/g, ' ')
    .trim();
}

function _truncate(text, max) {
  const s = String(text == null ? '' : text).trim();
  if (!max || s.length <= max) return s;
  return s.slice(0, Math.max(1, max - 1)) + '…';
}

/**
 * Parse a depends_on value into a list of ids.
 *
 * roadmap.cjs normalises depends_on to a comma-joined *string* rather than an
 * array, so this accepts both shapes. Reading only the array form would silently
 * drop every edge coming through parseRoadmap — the graph would render with no
 * dependencies at all and look correct.
 */
function parseDependsOn(value) {
  if (value == null) return [];
  const list = Array.isArray(value) ? value : String(value).split(',');
  return list
    .map((s) => String(s).trim())
    .filter((s) => s && s.toLowerCase() !== 'none' && s !== '-');
}

/**
 * Build an intermediate graph: nodes plus edges, independent of output format.
 *
 * @param {object[]} milestones [{id, name, status, depends_on, slices: [{id, name, status, tasks: [{id, name, status, depends_on}]}]}]
 * @param {object} [opts] {level, maxLabel}
 */
function buildGraph(milestones, opts) {
  const o = opts || {};
  const level = o.level || 'task';
  if (!LEVELS.includes(level)) {
    throw _err('roadmap-graph-bad-level', 'level must be one of ' + LEVELS.join(' | '), { level });
  }
  const maxLabel = Number.isInteger(o.maxLabel) && o.maxLabel > 0 ? o.maxLabel : 44;
  const depth = LEVELS.indexOf(level);

  const nodes = [];
  const edges = [];
  const clusters = [];
  const known = new Set();
  const dangling = [];

  const list = Array.isArray(milestones) ? milestones : [];

  for (const ms of list) {
    if (!ms || typeof ms.id !== 'string' || !ms.id) continue;
    const msNode = nodeId('M', ms.id);
    nodes.push({
      key: msNode,
      level: 'milestone',
      raw_id: ms.id,
      label: ms.name ? ms.id + ': ' + _truncate(ms.name, maxLabel) : ms.id,
      status: ms.status || 'pending',
      class: statusClass(ms.status),
    });
    known.add(ms.id);

    if (depth === 0) continue;

    const sliceKeys = [];
    for (const sl of (Array.isArray(ms.slices) ? ms.slices : [])) {
      if (!sl || typeof sl.id !== 'string' || !sl.id) continue;
      const slNode = nodeId('S', _qualify(ms.id, sl.id));
      nodes.push({
        key: slNode,
        level: 'slice',
        raw_id: sl.id,
        parent: msNode,
        label: sl.name ? sl.id + ': ' + _truncate(sl.name, maxLabel) : sl.id,
        status: sl.status || 'pending',
        class: statusClass(sl.status),
      });
      sliceKeys.push(slNode);

      if (depth < 2) continue;

      const taskKeys = [];
      const tasksById = new Map();
      for (const t of (Array.isArray(sl.tasks) ? sl.tasks : [])) {
        const tid = t && (typeof t === 'string' ? t : t.id);
        if (typeof tid !== 'string' || !tid) continue;
        const tNode = nodeId('T', _qualify(_qualify(ms.id, sl.id), tid));
        const meta = typeof t === 'string' ? {} : t;
        nodes.push({
          key: tNode,
          level: 'task',
          raw_id: tid,
          parent: slNode,
          label: meta.name ? tid + ': ' + _truncate(meta.name, maxLabel) : tid,
          status: meta.status || 'pending',
          class: statusClass(meta.status),
        });
        taskKeys.push(tNode);
        // Index under both spellings. A task's own depends_on names siblings by
        // their local id (`T0002`) while the node id is the full id
        // (`M001-S001-T0002`); keying on only one of them silently resolves no
        // edges and renders a wave that looks fully parallel when it is not.
        tasksById.set(tid, tNode);
        if (meta.local_id && meta.local_id !== tid) tasksById.set(meta.local_id, tNode);
      }

      // Task-level depends_on, resolved inside the slice. Tasks in one slice are
      // a parallel wave, so an intra-wave edge is the exception worth drawing.
      for (const t of (Array.isArray(sl.tasks) ? sl.tasks : [])) {
        if (!t || typeof t === 'string') continue;
        const to = tasksById.get(t.id);
        if (!to) continue;
        for (const dep of parseDependsOn(t.depends_on)) {
          const from = tasksById.get(dep);
          // A self-edge would come from a task listing itself, which Graphviz
          // draws as a loop and Mermaid as a cycle; neither is meaningful.
          if (from && from !== to) edges.push({ from, to, kind: 'task-depends' });
        }
      }

      clusters.push({ key: slNode, label: sl.id, members: taskKeys });
    }

    // Slices are serial waves: S001 → S002 → S003. This is the ordering the
    // executor actually enforces, and it is nowhere in roadmap.yaml as an
    // explicit edge — it is implied by list order, which is exactly the kind of
    // thing a diagram should make visible.
    for (let i = 1; i < sliceKeys.length; i += 1) {
      edges.push({ from: sliceKeys[i - 1], to: sliceKeys[i], kind: 'wave' });
    }

    if (sliceKeys.length) {
      edges.push({ from: msNode, to: sliceKeys[0], kind: 'contains' });
    }

    const declaredSliceKeys = new Set(sliceKeys);

    // Conditional slice edges (ADR-0028). A gated slice is the single most
    // important thing to see in a roadmap diagram — it is the one place where
    // reading the list top to bottom gives the wrong answer about what will run —
    // so it gets its own edge style and carries the condition as the label.
    for (const sl of (Array.isArray(ms.slices) ? ms.slices : [])) {
      if (!sl || typeof sl.id !== 'string' || !sl.id) continue;
      if (sl.when === undefined || sl.when === null) continue;
      const to = nodeId('S', _qualify(ms.id, sl.id));
      let terms;
      try {
        terms = conditions.normalizeCondition(sl.when, { milestone: ms.id, slice: sl.id }).terms;
      } catch {
        // A malformed condition is `slice-plan lint`'s finding to report, not
        // this renderer's. Skipping the edge here is safe because the lint
        // refuses the milestone outright, so no drawing of it can mislead.
        continue;
      }
      for (const term of terms) {
        const fromKey = nodeId('S', _qualify(ms.id, term.slice));
        if (fromKey === to) continue;
        if (!declaredSliceKeys.has(fromKey)) {
          dangling.push({
            from: term.slice, to: sl.local_id || sl.id, kind: 'slice-condition', milestone: ms.id,
          });
          continue;
        }
        edges.push({
          from: fromKey,
          to,
          kind: 'condition',
          label: term.op === 'status_not' ? 'unless ' + term.value : 'if ' + term.value,
        });
      }
    }
  }

  // Milestone dependencies, second pass so a forward reference resolves.
  for (const ms of list) {
    if (!ms || typeof ms.id !== 'string' || !ms.id) continue;
    for (const dep of parseDependsOn(ms.depends_on)) {
      if (!known.has(dep)) {
        // Report rather than draw. An edge to a milestone that does not exist is
        // a defect in roadmap.yaml, and silently omitting it would hide it.
        dangling.push({ from: dep, to: ms.id, kind: 'milestone-depends' });
        continue;
      }
      edges.push({ from: nodeId('M', dep), to: nodeId('M', ms.id), kind: 'milestone-depends' });
    }
  }

  return {
    level,
    nodes,
    edges,
    clusters,
    dangling_dependencies: dangling,
    stats: {
      milestones: nodes.filter((n) => n.level === 'milestone').length,
      slices: nodes.filter((n) => n.level === 'slice').length,
      tasks: nodes.filter((n) => n.level === 'task').length,
      edges: edges.length,
      dangling: dangling.length,
    },
  };
}

function _mermaidShape(node) {
  // Shape carries the level so the diagram is readable without the legend:
  // milestones are stadium-shaped, slices rectangles, tasks rounded.
  if (node.level === 'milestone') return ['([', '])'];
  if (node.level === 'slice') return ['[', ']'];
  return ['(', ')'];
}

/**
 * Render Mermaid `flowchart`. Subgraphs group tasks under their slice, which is
 * what makes a wave visible as a block rather than a row of unrelated boxes.
 */
function renderMermaid(graph, opts) {
  const o = opts || {};
  const direction = o.direction === 'LR' ? 'LR' : 'TD';
  const g = graph;
  const lines = [];
  lines.push('%% ' + GENERATED_HEADER);
  lines.push('flowchart ' + direction);

  const emitted = new Set();

  const emitNode = (n, indent, label) => {
    const [open, close] = _mermaidShape(n);
    lines.push(indent + n.key + open + '"' + escapeMermaid(label == null ? n.label : label) + '"' + close);
    emitted.add(n.key);
  };

  for (const ms of g.nodes.filter((n) => n.level === 'milestone')) {
    emitNode(ms, '  ');
    const slices = g.nodes.filter((n) => n.level === 'slice' && n.parent === ms.key);
    for (const sl of slices) {
      const tasks = g.nodes.filter((n) => n.level === 'task' && n.parent === sl.key);
      if (tasks.length === 0) {
        emitNode(sl, '  ');
        continue;
      }
      // A subgraph id must differ from every node id, or Mermaid renders the
      // subgraph and the node as one element and the wave edges vanish.
      lines.push('  subgraph cluster_' + sl.key + '["' + escapeMermaid(sl.label) + '"]');
      lines.push('    direction ' + (direction === 'TD' ? 'LR' : 'TD'));
      // The slice node is declared INSIDE its own cluster and is the anchor the
      // wave edges attach to. Marking it emitted without declaring it — which is
      // what the first version did — left every wave edge pointing at a node the
      // diagram never defines: Mermaid then invents an unstyled phantom box and
      // DOT silently creates a stray node outside the cluster.
      emitNode(sl, '    ', sl.raw_id);
      for (const t of tasks) emitNode(t, '    ');
      lines.push('  end');
    }
  }

  // Any node not reached above (a malformed parent chain) still gets emitted, so
  // an edge never references an undeclared node.
  for (const n of g.nodes) {
    if (!emitted.has(n.key)) emitNode(n, '  ');
  }

  lines.push('');
  for (const e of g.edges) {
    if (e.kind === 'condition') {
      // Dotted with the condition as the label: reading the slice list top to
      // bottom gives the wrong answer here, so the gate must be unmissable.
      lines.push('  ' + e.from + ' -. "' + escapeMermaid(e.label || 'if') + '" .-> ' + e.to);
      continue;
    }
    if (e.kind === 'contains') {
      lines.push('  ' + e.from + ' --- ' + e.to);
      continue;
    }
    const arrow = e.kind === 'wave' ? '==>' : '-->';
    lines.push('  ' + e.from + ' ' + arrow + ' ' + e.to);
  }

  lines.push('');
  for (const [cls, style] of Object.entries(CLASS_STYLE)) {
    lines.push('  classDef ' + cls + ' fill:' + style.fill + ',stroke:' + style.stroke
      + ',color:' + style.font + ',stroke-width:1px');
  }
  for (const cls of Object.keys(CLASS_STYLE)) {
    const members = g.nodes.filter((n) => n.class === cls).map((n) => n.key);
    // `class a,b,c name` with an empty list is a Mermaid parse error.
    if (members.length) lines.push('  class ' + members.join(',') + ' ' + cls);
  }

  return lines.join('\n');
}

/**
 * Render Graphviz DOT. Slices become real clusters, which gives the layout engine
 * the grouping information Mermaid can only approximate.
 */
function renderDot(graph, opts) {
  const o = opts || {};
  const g = graph;
  const lines = [];
  lines.push('// ' + GENERATED_HEADER);
  lines.push('digraph roadmap {');
  lines.push('  rankdir=' + (o.direction === 'LR' ? 'LR' : 'TB') + ';');
  lines.push('  node [shape=box style="rounded,filled" fontname="Helvetica" fontsize=10];');
  lines.push('  edge [fontname="Helvetica" fontsize=9];');
  lines.push('');

  const style = (n, label) => {
    const s = CLASS_STYLE[n.class] || CLASS_STYLE.pending;
    const shape = n.level === 'milestone' ? 'box3d' : (n.level === 'slice' ? 'box' : 'box');
    return '[label="' + escapeDot(label == null ? n.label : label) + '" fillcolor="' + s.fill
      + '" color="' + s.stroke + '" fontcolor="' + s.font + '" shape=' + shape + ']';
  };

  const emitted = new Set();
  for (const ms of g.nodes.filter((n) => n.level === 'milestone')) {
    lines.push('  ' + ms.key + ' ' + style(ms) + ';');
    emitted.add(ms.key);
    for (const sl of g.nodes.filter((n) => n.level === 'slice' && n.parent === ms.key)) {
      const tasks = g.nodes.filter((n) => n.level === 'task' && n.parent === sl.key);
      if (tasks.length === 0) {
        lines.push('  ' + sl.key + ' ' + style(sl) + ';');
        emitted.add(sl.key);
        continue;
      }
      lines.push('  subgraph cluster_' + sl.key + ' {');
      lines.push('    label="' + escapeDot(sl.label) + '";');
      lines.push('    style="rounded,dashed"; color="#95a5a6";');
      // Same anchor rule as the Mermaid path: the slice node is declared inside
      // its cluster so wave edges have a real endpoint. DOT cannot draw an edge
      // to a cluster directly.
      lines.push('    ' + sl.key + ' ' + style(sl, sl.raw_id) + ';');
      emitted.add(sl.key);
      for (const t of tasks) {
        lines.push('    ' + t.key + ' ' + style(t) + ';');
        emitted.add(t.key);
      }
      lines.push('  }');
    }
  }
  for (const n of g.nodes) {
    if (!emitted.has(n.key)) lines.push('  ' + n.key + ' ' + style(n) + ';');
  }

  lines.push('');
  for (const e of g.edges) {
    const attrs = e.kind === 'wave'
      ? '[style=bold color="#2c3e50" label="wave"]'
      : (e.kind === 'condition'
        ? '[style=dashed color="#b9770e" fontcolor="#b9770e" label="' + escapeDot(e.label || 'if') + '"]'
        : (e.kind === 'contains'
          ? '[style=dotted color="#95a5a6" arrowhead=none]'
          : '[color="#7f8c8d"]'));
    lines.push('  ' + e.from + ' -> ' + e.to + ' ' + attrs + ';');
  }
  lines.push('}');
  return lines.join('\n');
}

/**
 * Render into the requested format.
 */
function render(milestones, opts) {
  const o = opts || {};
  const format = o.format || 'mermaid';
  if (!FORMATS.includes(format)) {
    throw _err('roadmap-graph-bad-format', 'format must be one of ' + FORMATS.join(' | '), { format });
  }
  const graph = buildGraph(milestones, o);
  const text = format === 'dot' ? renderDot(graph, o) : renderMermaid(graph, o);
  return { format, text, graph, stats: graph.stats };
}

/**
 * Wrap a Mermaid diagram in the fence VitePress renders natively, so the output
 * can be pasted straight into a docs page.
 */
function toMarkdown(rendered, title) {
  const lines = [];
  if (title) {
    lines.push('## ' + title);
    lines.push('');
  }
  if (rendered.format !== 'mermaid') {
    // A DOT graph has no native renderer in Markdown; fencing it as `dot` at
    // least gets syntax highlighting instead of pretending it will draw.
    lines.push('```dot');
    lines.push(rendered.text);
    lines.push('```');
    return lines.join('\n');
  }
  lines.push('```mermaid');
  lines.push(rendered.text);
  lines.push('```');
  return lines.join('\n');
}

module.exports = {
  FORMATS,
  LEVELS,
  STATUS_CLASSES,
  CLASS_STYLE,
  GENERATED_HEADER,
  statusClass,
  nodeId,
  escapeMermaid,
  escapeDot,
  parseDependsOn,
  buildGraph,
  renderMermaid,
  renderDot,
  render,
  toMarkdown,
};
